---
sidebar: sidebar 
permalink: whats-new.html 
keywords: 'what"s new, features, new, release notes, enhancements, fixes, new features, backup and recovery, ontap clusters, alerts, identity and access management, iam, recovery, netapp console local deployment, console local, local' 
summary: NetApp 콘솔 로컬 배포에 포함된 기능 및 데이터 서비스의 최신 변경 사항에 대해 알아보십시오. 
---
= NetApp Console 로컬 배포의 최근 변경 사항
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
NetApp Console 로컬 배포에 포함된 기능 및 데이터 서비스의 최신 변경 사항에 대해 알아보십시오.



[[10-august-2026]]
== 2026년 8월 10일



[[netapp-console-local-deployment]]
=== NetApp Console 로컬 배포



==== NetApp Console 로컬 배포 소개

https://docs.netapp.com/us-en/console-local/concept-netapp-console-local.html["NetApp Console 로컬 배포 알아보기"].



[[backup-and-recovery]]
=== 백업 및 복구



==== 일반 NetApp Backup and Recovery 기능 향상

* *NetApp Console 로컬 배포 지원*: 이번 NetApp Backup and Recovery 릴리스는 NetApp Console 로컬 배포를 미리 보기 상태로 지원합니다.
* *90일 작업 보존*: 이제 Backup and Recovery가 작업 모니터에서 작업 정보를 90일 동안 보존합니다.




==== VMware 워크로드 개선 사항

이번 릴리스에서 VMware 워크로드는 다음과 같은 개선 사항을 도입했습니다.

* *SAN VM에 대한 대체 위치 복원 지원*: 이제 SAN 기반 VM 백업을 다른 위치로 복원할 수 있습니다.
* *여러 백업 삭제 지원*: 이제 한 번에 여러 백업을 삭제할 수 있습니다.


VMware 워크로드 보호에 대한 자세한 내용은 https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-vmware-protect-overview.html["VMware 워크로드 보호 개요"]을 참조하십시오.



==== Kubernetes 워크로드 개선 사항

이번 릴리스에서 Kubernetes 워크로드는 다음과 같은 개선 사항을 도입했습니다.

* *에어갭 리소스에 대한 미리 보기 지원*: NetApp Console 로컬 배포에서 NetApp Backup and Recovery를 실행하는 경우 에어갭 Kubernetes 리소스를 검색, 보호 및 복원할 수 있습니다. 이 기능은 이번 릴리스에서 미리 보기로 제공됩니다.


Kubernetes 워크로드 보호에 대한 자세한 내용은 https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-kubernetes-protect-overview.html["Kubernetes 워크로드 보호 개요"]을 참조하세요.



==== ONTAP Volumes 워크로드 개선 사항

이번 릴리스에서 ONTAP Volumes 워크로드는 다음과 같은 개선 사항을 도입했습니다.

* *복원 작업을 백업보다 우선 순위 지정*: 이제 가상 머신이나 파일을 복원할 때 복원 작업을 백업 작업보다 우선 순위로 지정할 수 있습니다.
* *Backup and Recovery 활성화 없이 ONTAP 시스템 및 볼륨 검색*: 이제 Backup and Recovery를 활성화하지 않고도 시스템과 볼륨을 검색할 수 있습니다.


ONTAP Volumes 워크로드 보호에 대한 자세한 내용은 https://docs.netapp.com/us-en/data-services-backup-recovery/prev-ontap-protect-overview.html["ONTAP 볼륨 워크로드 보호 개요"]를 참조하십시오.



[[13-july-2026]]
== 2026년 7월 13일



[[backup-and-recovery]]
=== 백업 및 복구



==== 모든 워크로드에 대한 향상된 멀티 버킷 지원

NetApp Backup and Recovery는 이제 서로 다른 클라우드 공급자에 걸쳐 최대 100개의 버킷을 사용하여 시스템 내 워크로드를 보호하는 기능을 지원합니다. 시스템당 6개 이상의 버킷을 지원하려면 ONTAP 9.19.1 이상 버전이 필요합니다.

NetApp Backup and Recovery에 대한 자세한 내용은  https://docs.netapp.com/us-en/data-services-backup-recovery/concept-backup-to-cloud.html["NetApp Backup and Recovery에 대해 알아보세요"]을 참조하십시오.



[[15-june-2026]]
== 2026년 6월 15일



[[backup-and-recovery]]
=== 백업 및 복구



==== Kubernetes 워크로드 개선 사항

이번 릴리스에서 Kubernetes 워크로드는 다음과 같은 개선 사항을 도입했습니다.

* *Trident Protect 26.06*: 이번 릴리스에는 Trident Protect 26.06가 포함되어 있습니다.
* *복원 중 애플리케이션 생성 건너뛰기*: 이제 복원 작업 중 애플리케이션 사용자 지정 리소스 개체의 자동 생성을 건너뛸 수 있습니다. 이렇게 하면 애플리케이션 인벤토리에 불필요한 항목이 줄어듭니다.
* *VM 영구 볼륨 클레임 복원*: VM 기반 애플리케이션을 복원할 때 이제 전체 가상 머신을 복원하지 않고 개별 영구 볼륨 클레임을 복원할 수 있으므로 특정 디스크 또는 볼륨이 손상되거나 데이터가 손실된 경우 복구 속도가 향상됩니다.
* *작업 모니터링 개선 사항*: 이제 작업 모니터링을 통해 Kubernetes 보호 작업에 대한 가시성이 향상되었습니다. 작업 및 하위 작업에 대한 자세한 상태 정보를 확인하고 각 작업에서 사용되는 대상 스토리지를 볼 수 있습니다.


Kubernetes 워크로드 보호에 대한 자세한 내용은 https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-kubernetes-protect-overview.html["Kubernetes 워크로드 보호 개요"]을 참조하세요.



[[08-june-2026]]
== 2026년 6월 8일



[[backup-and-recovery]]
=== 백업 및 복구



==== ONTAP Volumes 워크로드 개선 사항

이번 릴리스에서 ONTAP Volumes 워크로드는 다음과 같은 개선 사항을 도입했습니다.

*S3 호환 클라우드 스토리지 지원*: NetApp Backup and Recovery for Volumes 워크로드가 이제 S3 호환 클라우드 스토리지로의 백업을 지원합니다.

ONTAP Volumes 워크로드 보호에 대한 자세한 내용은 https://docs.netapp.com/us-en/data-services-backup-recovery/prev-ontap-protect-overview.html["ONTAP 볼륨 워크로드 보호 개요"]를 참조하십시오.



==== Hyper-V 워크로드 개선 사항

이번 릴리스에서 Hyper-V 워크로드는 다음과 같은 개선 사항을 도입했습니다.

* *게스트 VM으로 파일 및 폴더 복원 기능 개선*: 이제 기본 또는 2차 스토리지의 스냅샷에서 게스트 Windows VM으로 파일 및 폴더를 복원할 수 있습니다. 이 기능은 CIFS 및 SAN VM에서 지원됩니다.
* *보호 그룹이 이제 호스트 시간대 스케줄링을 사용합니다*: 보호 그룹은 이제 Hyper-V 호스트의 시간대를 사용합니다. 호스트 시간대 스케줄링이 도입되기 전에 생성된 보호 그룹은 이전에 구성된 시간(일반적으로 UTC)을 계속 사용합니다. 이러한 보호 그룹이 Hyper-V 호스트 시간대를 사용하도록 업데이트하려면 스케줄을 다시 생성해야 합니다. 자세한 내용은 https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-hyperv-protection-groups.html["Hyper-V 워크로드용 보호 그룹 생성 및 관리"]을 참조하십시오.


Hyper-V 워크로드 보호에 대한 자세한 내용은 https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-hyperv-protect-overview.html["NetApp Backup and Recovery를 사용한 Hyper-V 보호 워크플로"]를 참조하십시오.



==== VMware 워크로드 개선 사항

이번 릴리스에서 VMware 워크로드는 다음과 같은 개선 사항을 도입했습니다.

* *보호 그룹이 이제 호스트 시간대 스케줄링을 사용합니다*: 보호 그룹은 이제 호스팅 VMware vCenter Server의 시간대를 사용합니다. 호스트 시간대 스케줄링이 도입되기 전에 생성된 보호 그룹은 이전에 구성된 시간대(일반적으로 UTC)에서 계속 실행됩니다. vCenter 시간대를 사용하려면 스케줄을 다시 생성해야 합니다. 자세한 내용은 https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-vmware-protection-groups.html["VMware 워크로드용 보호 그룹 생성 및 관리"]을 참조하십시오.


VMware 워크로드 보호에 대한 자세한 내용은 https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-vmware-protect-overview.html["VMware 워크로드 보호 개요"]을 참조하십시오.
